"""Markdown report generation from score results."""

from pathlib import Path
from typing import Any

from .utils import read_json, write_text


DISCLAIMER = (
    "> **Research only.** This report is generated from synthetic demo data "
    "and is not financial advice. No real market data or trading signals are implied. "
    "Scores reflect evaluation against a synthetic benchmark dataset only."
)


def _pct_str(v: float) -> str:
    return f"{v * 100:.1f}%"


def generate_report(
    score_path: str | Path,
    output_path: str | Path,
) -> str:
    data: dict[str, Any] = read_json(score_path)

    model = data.get("model", "unknown")
    dataset = data.get("dataset", "unknown")
    total = data.get("total", 0)
    overall = data.get("overall", 0.0)
    direction = data.get("direction_accuracy", 0.0)
    event_type = data.get("event_type_accuracy", 0.0)
    asset_match = data.get("asset_match", 0.0)
    time_horizon = data.get("time_horizon_match", 0.0)
    correct_dir = data.get("correct_direction", 0)
    correct_evt = data.get("correct_event_type", 0)
    correct_asset = data.get("correct_asset", 0)
    correct_horizon = data.get("correct_time_horizon", 0)
    failed = data.get("failed_examples", [])
    notes = data.get("notes", "")

    lines: list[str] = []
    lines.append(f"# Score Report — {model}\n")
    lines.append(DISCLAIMER)
    lines.append("")
    lines.append("## Summary\n")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| Model | `{model}` |")
    lines.append(f"| Dataset | `{dataset}` |")
    lines.append(f"| Total Examples | {total} |")
    lines.append(f"| **Overall Score** | **{_pct_str(overall)}** |")
    lines.append("")
    lines.append("## Metric Breakdown\n")
    lines.append("| Metric | Score | Correct / Total |")
    lines.append("|--------|-------|-----------------|")
    lines.append(f"| Direction Accuracy | {_pct_str(direction)} | {correct_dir} / {total} |")
    lines.append(f"| Event Type Accuracy | {_pct_str(event_type)} | {correct_evt} / {total} |")
    lines.append(f"| Asset Match | {_pct_str(asset_match)} | {correct_asset} / {total} |")
    lines.append(f"| Time Horizon Match | {_pct_str(time_horizon)} | {correct_horizon} / {total} |")
    lines.append("")

    if failed:
        lines.append(f"## Failed Examples ({len(failed)})\n")
        lines.append(
            "The following examples had incorrect direction predictions:\n"
        )
        lines.append("| ID | Headline | Expected | Predicted | Asset |")
        lines.append("|----|----------|----------|-----------|-------|")
        for ex in failed[:20]:
            headline = ex.get("headline", "")[:60].replace("|", "—")
            lines.append(
                f"| {ex.get('id','')} "
                f"| {headline} "
                f"| {ex.get('expected_direction','')} "
                f"| {ex.get('predicted_direction','')} "
                f"| {ex.get('asset','')} |"
            )
        if len(failed) > 20:
            lines.append(f"\n_...and {len(failed) - 20} more._")
        lines.append("")

    if notes:
        lines.append("## Notes\n")
        lines.append(notes)
        lines.append("")

    lines.append("## Limitations\n")
    lines.append(
        "- Scores are computed against a synthetic 32-row demo dataset.\n"
        "- Direction accuracy is the primary signal; other metrics are supplementary.\n"
        "- Reasoning quality is not evaluated in v0.1.\n"
        "- Results should not be used to compare real model performance.\n"
        "- This report does not constitute financial advice of any kind.\n"
    )
    lines.append("")
    lines.append("---")
    lines.append("_Generated by News2SignalLab v0.1.0 — © 2024-2026 Catalayer AI — Apache-2.0_")

    content = "\n".join(lines)
    write_text(output_path, content)
    return content
